//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEducation> tblEducations { get; set; }
        public virtual DbSet<tblResumeData> tblResumeDatas { get; set; }
        public virtual DbSet<tblInwardWO> tblInwardWOes { get; set; }
        public virtual DbSet<tblProjectMaster> tblProjectMasters { get; set; }
        public virtual DbSet<tblFilter> tblFilters { get; set; }
        public virtual DbSet<tblCorrespondence> tblCorrespondences { get; set; }
        public virtual DbSet<tblDrawing> tblDrawings { get; set; }
        public virtual DbSet<tblReport> tblReports { get; set; }
        public virtual DbSet<tblOutwardWO> tblOutwardWOes { get; set; }
        public virtual DbSet<tblBGsData> tblBGsDatas { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblInvoiceConsultant> tblInvoiceConsultants { get; set; }
        public virtual DbSet<tblInvoiceData> tblInvoiceDatas { get; set; }
        public virtual DbSet<tblVendorAllocation> tblVendorAllocations { get; set; }
        public virtual DbSet<tblVendorData> tblVendorDatas { get; set; }
    }
}
