//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblBGsData
    {
        public int Id { get; set; }
        public System.Guid BGsId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string TypeOfService { get; set; }
        public string WONo { get; set; }
        public Nullable<System.DateTimeOffset> WODate { get; set; }
        public Nullable<int> TypeOfBG { get; set; }
        public string WOValue { get; set; }
        public string NameOfBeneficiary { get; set; }
        public string Address { get; set; }
        public string Purpose { get; set; }
        public string BGNo { get; set; }
        public Nullable<System.DateTimeOffset> BGDate { get; set; }
        public Nullable<System.DateTimeOffset> BGEffectiveDate { get; set; }
        public Nullable<System.DateTimeOffset> EndDateOfClaim { get; set; }
        public string BGValue { get; set; }
        public string IssuingBank { get; set; }
        public string IssuingBranch { get; set; }
        public string IssuingAddress { get; set; }
        public string BeneficiaryBank { get; set; }
        public string BeneficiaryBranch { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string ReferenceContract { get; set; }
        public Nullable<System.DateTimeOffset> ValidDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidTo { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }

        [NotMapped]
        public HttpPostedFileBase File { set; get; }

        [NotMapped]
        public bool IsFileAttached { set; get; }
    }
}
