//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblCorrespondence
    {
        public int Id { get; set; }
        public System.Guid CorrespondenceId { get; set; }
        public int CorrespondenceType { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> Department { get; set; }
        public string ProjectName { get; set; }
        public string FromName { get; set; }
        public string FromDesignation { get; set; }
        public string FromOrganisation { get; set; }
        public string FromAddress { get; set; }
        public string ToName { get; set; }
        public string ToDesignation { get; set; }
        public string ToOrganisation { get; set; }
        public string ToAddress { get; set; }
        public string CopyToName { get; set; }
        public string CopyToDesignation { get; set; }
        public string CopyToOrganisation { get; set; }
        public string CopyToAddress { get; set; }
        public string Subject { get; set; }
        public string LetterNo { get; set; }
        public Nullable<System.DateTimeOffset> LetterDate { get; set; }
        public string Reference1 { get; set; }
        public Nullable<System.DateTimeOffset> ReferenceDate1 { get; set; }
        public string Reference2 { get; set; }
        public Nullable<System.DateTimeOffset> ReferenceDate2 { get; set; }
        public string Reference3 { get; set; }
        public Nullable<System.DateTimeOffset> ReferenceDate3 { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> ReceivedThrough { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedDate { get; set; }
        public string EmailID1 { get; set; }
        public string EmailID2 { get; set; }
        public string EmailID3 { get; set; }
        public Nullable<int> ReceivedType { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedDate1 { get; set; }
        public string ReceivedBy1 { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedDate2 { get; set; }
        public string ReceivedBy2 { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { set; get; }
    }
}
