//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using PMS.Areas.PMS.Models;
    using PMS.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblEducation
    {
        public int Id { get; set; }
        public System.Guid EducationId { get; set; }
        public System.Guid ResumeId { get; set; }
        public string Qualification { get; set; }
        public string University { get; set; }
        public string Year { get; set; }
        public string Course { get; set; }
        public string Specialisation { get; set; }
        public Nullable<int> EducationType { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public bool isDelete { set; get; }

        [NotMapped]
        private List<FilterEntity> _listQualifications { set; get; }
        [NotMapped]
        public List<FilterEntity> ListQualifications
        {
            get
            {
                if (_listQualifications == null)
                {
                    _listQualifications = CommonFunctions.Instance.getQualifications();
                }
                return _listQualifications;
            }
        }

    }
}
