//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilter
    {
        public int Id { get; set; }
        public string FilterCode { get; set; }
        public string FilterName { get; set; }
        public string FilterType { get; set; }
        public Nullable<bool> FilterEnable { get; set; }
        public string ParentFilterCode { get; set; }
    }
}
