//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblInwardWO
    {
        public int Id { get; set; }
        public System.Guid WOId { get; set; }
        public string BranchCode { get; set; }
        public string BranchLocation { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> TypeofService { get; set; }
        public string ProjectName { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public string WorkOrderValue { get; set; }
        public string WOPath { get; set; }
        public string ClientName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string ContactPerson1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string InvoiceName { get; set; }
        public string BilligAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingState { get; set; }
        public string BillingPiCode { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string Other { get; set; }
        public string ScopeofService { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { set; get; }
    }
}
