//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblInvoiceData
    {
        public int Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> TypeOfInvoice { get; set; }
        public string Description { get; set; }
        public string InvoiceAmount { get; set; }
        public Nullable<System.DateTimeOffset> InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string CGSTAmount { get; set; }
        public string SGSTAmount { get; set; }
        public string IGST { get; set; }
        public string TotalInvoiceAmount { get; set; }
        public string Status { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { set; get; }

        [NotMapped]
        public bool IsFileAttached { set; get; }
    }
}
