//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectMaster
    {
        public int PROJECTID { get; set; }
        public string PROJECTCODE { get; set; }
        public string PROJECTNAME { get; set; }
        public string BRANCHCODE { get; set; }
        public string BRANCHCODETYPE { get; set; }
        public string DIVISION { get; set; }
        public string PROJECTTYPE { get; set; }
        public string TYPEOFSERVICE { get; set; }
        public string WORKORDERNO { get; set; }
        public string WORKORDERDATE { get; set; }
        public string WORKORDERVALUE { get; set; }
        public string WORKORDERPATH { get; set; }
        public string CLIENTNAME { get; set; }
        public string CLIENTAddress1 { get; set; }
        public string CLIENTAddress2 { get; set; }
        public string ContactPerson1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string ContactNo1 { get; set; }
        public string ContactNo2 { get; set; }
        public string Emailid1 { get; set; }
        public string Emailid2 { get; set; }
        public string EmployerName { get; set; }
        public string EmployerAddress1 { get; set; }
        public string EmployerAddress2 { get; set; }
        public string AuthorityEngineer { get; set; }
        public string EngineerAddress1 { get; set; }
        public string EngineerAddress2 { get; set; }
        public string ScopeofService { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    }
}
