//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblReport
    {
        public int Id { get; set; }
        public System.Guid ReportId { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> Department { get; set; }
        public string ProjectName { get; set; }
        public string ReportNo { get; set; }
        public Nullable<System.DateTimeOffset> ReportDate { get; set; }
        public string ReportTitle { get; set; }
        public string Chainage { get; set; }
        public Nullable<System.DateTimeOffset> DateOfSubmission { get; set; }
        public string SubmittedTo { get; set; }
        public string SoftHardCopy { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string Comments { get; set; }
        public string ViaEmailLetter { get; set; }
        public Nullable<System.DateTimeOffset> OtherDate { get; set; }
        public string RevisionNo { get; set; }
        public Nullable<System.DateTimeOffset> RevisionDate { get; set; }
        public string OtherSubmittedTo { get; set; }
        public string OtherSoftHardCopy { get; set; }
        public string OtherFilePath { get; set; }
        public string OtherFileName { get; set; }
        public Nullable<System.DateTimeOffset> ApprovalDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { set; get; }

        [NotMapped]
        public HttpPostedFileBase OtherFile { set; get; }

        [NotMapped]
        public bool IsFileAttached { set; get; }

        [NotMapped]
        public bool IsOtherFileAttached { set; get; }
    }
}
