//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblResumeData
    {
        public int Id { get; set; }
        public System.Guid ResumeId { get; set; }
        public Nullable<System.DateTime> ResumeDate { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> Department { get; set; }
        public string ReceivedThrough { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> ExpYears { get; set; }
        public Nullable<int> ExpMonths { get; set; }
        public string PresentCompany { get; set; }
        public string Position { get; set; }
        public string PlaceOfWorking { get; set; }
        public Nullable<int> NoOfCompanies { get; set; }
        public Nullable<decimal> PresentSalary { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public string FatherName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string Email { get; set; }
        public string CVCompletePath { get; set; }
        public string CVPath { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        [NotMapped]
        public List<tblEducation> tblEducations { set; get; }

        [NotMapped]
        public HttpPostedFileBase File { set; get; }
    }
}
