//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string TempEmail { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string EmpId { get; set; }
        public Nullable<bool> Acive { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string IpAddress { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string VerifcationCode { get; set; }
        public Nullable<System.DateTimeOffset> VerifiedDateTime { get; set; }
        public string Other { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
