//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblVendorData
    {
        public int Id { get; set; }
        public System.Guid VendorId { get; set; }
        public Nullable<bool> TypeOfOwnership { get; set; }
        public string VendorName { get; set; }
        public string VendorCode { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTimeOffset> City { get; set; }
        public string Country { get; set; }
        public string TelephoneNo { get; set; }
        public string Website { get; set; }
        public string state { get; set; }
        public string PinNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public string AuthorisedRepresentative { get; set; }
        public string Designation1 { get; set; }
        public string Designation2 { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string EmailId1 { get; set; }
        public string EmailId2 { get; set; }
        public string AlternateContactPerson { get; set; }
        public string ServicesOfVendor { get; set; }
        public string VendorNameAsPerBak { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNo { get; set; }
        public string PanNo { get; set; }
        public string MSMENo { get; set; }
        public string GSTINNo { get; set; }
        public string CINNo { get; set; }
        public Nullable<bool> IsPanCard { get; set; }
        public string PanCardPath { get; set; }
        public string PanCardName { get; set; }
        public Nullable<bool> IsCertificateofIncorporation { get; set; }
        public string CertificateofIncorporationPath { get; set; }
        public string CertificateofIncorporationName { get; set; }
        public Nullable<bool> IsCompanyProfile { get; set; }
        public string CompanyProfilePath { get; set; }
        public string CompanyProfileName { get; set; }
        public Nullable<bool> IsGSTCertificate { get; set; }
        public string GSTCertificatePath { get; set; }
        public string GSTCertificateName { get; set; }
        public Nullable<bool> IsCancelledheque { get; set; }
        public string CancelledhequePath { get; set; }
        public string CancelledhequeName { get; set; }
        public Nullable<bool> IsCMSME { get; set; }
        public string MSMEPath { get; set; }
        public string MSMEName { get; set; }
        public Nullable<bool> IsFile { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }

        [NotMapped]
        public bool PanCard { set; get; }
        [NotMapped]
        public bool CertificateofIncorporation { set; get; }
        [NotMapped]
        public bool CompanyProfile { set; get; }
        [NotMapped]
        public bool GSTCertificate { set; get; }
        [NotMapped]
        public bool Cancelledheque { set; get; }
        [NotMapped]
        public bool MSME { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachPanCard { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachCertificateofIncorporation { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachCompanyProfile { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachGSTCertificate { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachCancelledheque { set; get; }
        [NotMapped]
        public HttpPostedFileBase AttachMSME { set; get; }
        [NotMapped]
        public HttpPostedFileBase FileAttach { set; get; }
    }
}
