//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblVendorAllocation
    {
        public int Id { get; set; }
        public System.Guid VendorAllocationId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> Activity { get; set; }
        public Nullable<bool> InHouseOutSource { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string WOValue { get; set; }
        public Nullable<System.DateTimeOffset> WODate { get; set; }
        public string WONo { get; set; }
        public string RevisedWOValue { get; set; }
        public string Amendment { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }

        [NotMapped]
        public HttpPostedFileBase File { set; get; }

        [NotMapped]
        public bool IsFileAttached { set; get; }
    }
}
